version: '3.8'

services:
  crms-backend:
    build:
      context: ./apps/backend/crms
      dockerfile: Dockerfile
    image: crms-backend:latest
    container_name: crms-backend-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=${SPRING_DATA_MONGODB_URI}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
